# Generated by Django 4.2.11 on 2024-03-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_customuser_listing_delete_savedlisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.TextField(default='nopassword'),
        ),
    ]
